// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrlndeurhpdvkdmovils.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybG5kZXVyaHBkdmtkbW92aWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTk5NDIsImV4cCI6MjA2ODE3NTk0Mn0.PnbC0Tdao90jG6hlGCKkD2_8yC-Vlb1C8TbgQkU34QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});